---
title: "rural.Rmd"
output: html_document
date: '2022-06-30'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(tidycensus)
library(ggthemes)
library(tigris)
```

##Map
This map details the percentage of rural areas in the United States.

```{r data_creation, echo = FALSE}
get_decennial(geography = "state",
              variables = c("P001001", "P002005"),
              year = 2010,
              output = "wide",
              geometry = TRUE)
```

```{r graph_cont_usa, echo = FALSE}
rural |>
  filter(! NAME %in% c("Alaska", "Hawaii", "Puerto Rico")) |>
  ggplot(aes(fill = 100*P002005/P001001)) +
  geom_sf() +
  scale_fill_viridis_c(option = "plasma",
                       direction = -1) +
  labs(title = "Rural geography of the Continental United States",
       caption = "Source: Census 2010",
       fill = "Percent Rural") +
  theme_void()
```

```{r graph_all_usa, echo = FALSE}}
rural_shifted |>
  shift_geometry() |>
  ggplot(aes(fill = 100*P002005/P001001)) +
  geom_sf() +
  scale_fill_viridis_c(option = "plasma",
                       direction = -1) +
  labs(title = "Rural geography of the United States",
       caption = "Source: Census 2010",
       fill = "Percent Rural") +
  theme_void()
```

